version: '3.8'

x-common:

  database:

    &db-environment

    # Do not remove the "&db-password" from the end of the line below, it is important

    # for Panel functionality.

    MYSQL_PASSWORD: &db-password "CHANGE_ME"

    MYSQL_ROOT_PASSWORD: "CHANGE_ME_TOO"

  panel:

    &panel-environment

    # This URL should be the URL that your reverse proxy routes to the panel server

    APP_URL: "https://pterodactyl.example.com"

    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php

    APP_TIMEZONE: "UTC"

    APP_SERVICE_AUTHOR: "noreply@example.com"

    TRUSTED_PROXIES: "*" # Set this to your proxy IP

    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt

    # to generate an SSL certificate for the Panel.

    # LE_EMAIL: ""

  mail:

    &mail-environment

    MAIL_FROM: "noreply@example.com"

    MAIL_DRIVER: "smtp"

    MAIL_HOST: "mail"

    MAIL_PORT: "1025"

    MAIL_USERNAME: ""

    MAIL_PASSWORD: ""

    MAIL_ENCRYPTION: "true"

 

#

# ------------------------------------------------------------------------------------------

# DANGER ZONE BELOW

#

# The remainder of this file likely does not need to be changed. Please only make modifications

# below if you understand what you are doing.

#

services:

  database:

    image: mariadb:10.5

    restart:  selalu

    command:  --default-authentication-plugin=mysql_native_password

    volumes:

      - "/srv/pterodactyl/database:/var/lib/mysql"

 lingkungan :

      <<:  *db-lingkungan

 Mysql_database  :   "panel"

 Mysql_user  :   "pterodactyl"

 Cache :

  gambar  :   redis:alpine

 restart  :   selalu

 panel :

  gambar  :   ghcr.io/pterodactyl/panel:terbaru

 restart  :   selalu

 port :

 - "80:80"

 - "443:443"

 link :

  -  database

  -  Cache

 volume :

  -  "/srv/pterodactyl/var/:/app/var/"

  -  "/srv/pterodactyl/nginx/:/etc/nginx/http.d/"

  -  "/srv/pterodactyl/certs/:/etc/letsencrypt/"

  -  "/srv/pterodactyl/logs/:/app/storage/logs"

 lingkungan :

  <<  :   [*panel-lingkungan, *mail-lingkungan]

 Db_password  :   *db-password

 App_env   :    "produksi"

 App_environment_only   :    "palsu"

 Cache_driver   :    "redis"

 Session_driver   :    "redis"

 Antrian_driver   :    "redis"

 Redis_host   :    "Cache"

 Db_host  :   "database"

 Db_port  :   "3306"

jaringan:

 default :

 ipam :

 config :

  -  subnet  :      # Daftar zona waktu yang valid dapat ditemukan di sini: http://php.net / manual / en / timezones.php     

